# services/pdf_generator.py
# Aesthetic PDF Generator for Content Strategist Audits using fpdf2.

from fpdf import FPDF
import datetime
import re

def safe_latin1(text: str) -> str:
    """
    Cleans Unicode text to be fully compatible with standard Latin-1 Helvetica font.
    Replaces common strategist emojis and markers with safe representations.
    """
    if not text:
        return ""
        
    replacements = {
        # Emojis & special strategist bullets
        "•": "-",
        "➔": "->",
        "→": "->",
        "🚀": "[GROWTH]",
        "🤖": "[AI]",
        "✅": "[OK]",
        "❌": "[ERROR]",
        "⚠️": "[WARNING]",
        "ℹ️": "[INFO]",
        "📊": "[METRICS]",
        "❤️": "[ENGAGEMENT]",
        "👥": "[AUDIENCE]",
        "🎬": "[CONTENT]",
        "👤": "[PROFILE]",
        "#️⃣": "#",
        "📋": "[AUDIT]",
        "🔮": "[PREDICTION]",
        "🧠": "[STRATEGY]",
        "🏆": "[TOP]",
        "💡": "[TIP]",
        "🌟": "[STAR]",
        "✨": "[AESTHETIC]",
        "🔥": "[VIRAL]",
        "📈": "[GROWTH]",
        "📉": "[DECREASE]",
        "🎯": "[GOAL]",
        "💪": "[STRENGTH]",
        
        # Smart quotes & dashes
        "\u201c": '"',
        "\u201d": '"',
        "\u2018": "'",
        "\u2019": "'",
        "\u2013": "-",
        "\u2014": "--",
        
        # Other common special punctuation
        "\u0393": "G", # gamma
        "\u00e7": "c",
        "\u00e9": "e",
        "\u00e1": "a",
        "\u00ed": "i",
        "\u00f3": "o",
        "\u00fa": "u",
        "\u00f1": "n",
    }
    
    for uni_char, safe_char in replacements.items():
        text = text.replace(uni_char, safe_char)
        
    # Standardize bullet shapes
    text = re.sub(r'[\u2022\u2023\u25CF\u25CB\u25AA\u25AB]', '-', text)
    
    # Final safety sweep: replace any other non-latin1 characters with space or standard marks
    cleaned_chars = []
    for char in text:
        try:
            char.encode("latin1")
            cleaned_chars.append(char)
        except UnicodeEncodeError:
            cleaned_chars.append(" ") # replace unsupported characters gracefully
            
    return "".join(cleaned_chars)


class AestheticAuditPDF(FPDF):
    """
    Custom styled FPDF class to generate premium-looking reports.
    """
    def __init__(self, creator_name="Creator"):
        super().__init__()
        self.creator_name = safe_latin1(creator_name)
        self.set_margins(18, 20, 18)
        self.set_auto_page_break(True, margin=20)
        
    def header(self):
        # Premium thin colored line at the top
        self.set_fill_color(124, 58, 237) # #7C3AED
        self.rect(0, 0, 210, 4, "F")
        
        # Header text
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(148, 163, 184) # #94A3B8
            self.cell(0, 8, f"AROHANUM ELEVATE  |  Instagram Strategy Audit for @{self.creator_name}", 0, 0, "L")
            self.cell(0, 8, f"Generated: {datetime.date.today().strftime('%B %d, %Y')}", 0, 1, "R")
            self.ln(5)

    def footer(self):
        # Footer thin line
        self.set_draw_color(226, 232, 240) # #E2E8F0
        self.set_line_width(0.2)
        self.line(18, 280, 192, 280)
        
        # Footer text
        self.set_y(-15)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, "AROHANUM ELEVATE  -  Confidential Growth Audit", 0, 0, "L")
        self.cell(0, 10, f"Page {self.page_no()}", 0, 0, "R")

    def chapter_title(self, label):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(124, 58, 237) # #7C3AED
        self.ln(4)
        
        # Drawing a nice pill badge style background for headers
        text_width = self.get_string_width(label) + 6
        self.set_fill_color(245, 243, 255) # Light Violet background
        self.rect(self.get_x() - 2, self.get_y() - 1, text_width, 8, "F")
        
        self.cell(0, 6, label, 0, 1, "L")
        self.ln(3)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(51, 65, 85) # Slate #334155
        self.multi_cell(0, 6, text)
        self.ln(2)


def generate_pdf_report(creator_name: str, report_text: str, metrics: dict) -> bytes:
    """
    Compiles report text and metrics into a beautiful styled PDF.
    
    Args:
        creator_name: The Instagram username.
        report_text: Plain-text analyst report generated by Gemini.
        metrics: Dict containing extracted metrics.
        
    Returns:
        bytes: The compiled PDF document in bytes.
    """
    creator_name = safe_latin1(creator_name)
    report_text = safe_latin1(report_text)
    
    pdf = AestheticAuditPDF(creator_name)
    
    # ── Page 1: Stunning Cover Page ──────────────────────────────────────────
    pdf.add_page()
    
    # Background accents
    pdf.set_fill_color(245, 243, 255) # Light Violet background block
    pdf.rect(10, 50, 190, 80, "F")
    
    # Title
    pdf.set_y(60)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(17, 24, 39) # Deep Navy
    pdf.cell(0, 10, "INSTAGRAM CREATOR AUDIT", 0, 1, "C")
    
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(124, 58, 237) # Purple
    pdf.cell(0, 10, f"GROWTH & CONTENT STRATEGY FOR @{creator_name.upper()}", 0, 1, "C")
    
    # Divider line
    pdf.set_draw_color(124, 58, 237)
    pdf.set_line_width(1)
    pdf.line(60, 85, 150, 85)
    
    # Meta / Info box
    pdf.set_y(100)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 116, 139) # Slate light
    pdf.cell(0, 6, "PREPARED BY AROHANUM ELEVATE STRATEGY TEAM", 0, 1, "C")
    pdf.cell(0, 6, f"DATE: {datetime.date.today().strftime('%B %d, %Y')}", 0, 1, "C")
    
    # Render key metric card blocks on cover page if available
    pdf.set_y(160)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 10, "CORE AUDIT HIGHLIGHTS", 0, 1, "L")
    pdf.ln(2)
    
    # Grid of highlight cards
    followers = metrics.get("profile_metrics", {}).get("followers")
    er = metrics.get("engagement_metrics", {}).get("engagement_rate")
    likes = metrics.get("engagement_metrics", {}).get("avg_likes")
    posts = metrics.get("profile_metrics", {}).get("posts")
    
    def fmt_val(v, suffix=""):
        if v is None: return "N/A"
        try:
            val = float(v)
            if val >= 1000000: return f"{val/1000000:.1f}M{suffix}"
            if val >= 1000: return f"{val/1000:.1f}K{suffix}"
            return f"{int(val):,}{suffix}"
        except:
            return f"{v}{suffix}"

    highlights = [
        ("Audience Size", fmt_val(followers)),
        ("Engagement Rate", fmt_val(er, "%")),
        ("Avg Likes", fmt_val(likes)),
        ("Total Posts", fmt_val(posts)),
    ]
    
    card_width = 41
    spacing = 3
    pdf.set_fill_color(248, 250, 252) # Clean soft gray card background
    pdf.set_draw_color(226, 232, 240) # Slate border
    pdf.set_line_width(0.3)
    
    start_x = 18
    for i, (label, val) in enumerate(highlights):
        x = start_x + i * (card_width + spacing)
        pdf.rect(x, 175, card_width, 24, "FD")
        
        # Card content
        pdf.set_xy(x, 179)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(124, 58, 237)
        pdf.cell(card_width, 5, val, 0, 1, "C")
        
        pdf.set_x(x)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(card_width, 5, label, 0, 1, "C")
        
    # Strategic Note at bottom
    pdf.set_xy(18, 215)
    pdf.set_fill_color(255, 247, 237) # Light Orange alert box
    pdf.set_draw_color(254, 215, 170)
    pdf.rect(18, 215, 174, 26, "FD")
    
    pdf.set_xy(22, 218)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(194, 65, 12) # Deep Orange
    pdf.cell(0, 5, "CONFIDENTIALITY & PURPOSE NOTE:", 0, 1, "L")
    pdf.set_x(22)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(127, 29, 29)
    pdf.multi_cell(166, 4.5, "This strategy audit is proprietary and prepared exclusively for growth development. It leverages advanced multi-point metric extraction and automated narrative reasoning to formulate actionable content recommendations.")

    # ── Page 2: Strategy Report Narrative ─────────────────────────────────────
    pdf.add_page()
    
    # Process and split the Gemini strategist report into sections
    lines = report_text.split("\n")
    current_section = []
    
    def flush_section():
        if not current_section:
            return
        
        header_text = current_section[0].strip()
        
        # Elegant header pattern matching
        is_header = False
        if re.match(r'^\d+\.\s+[A-Z\s&]+', header_text) or (header_text.isupper() and len(header_text) > 4):
            is_header = True
            
        if is_header:
            pdf.chapter_title(header_text)
            body = "\n".join(current_section[1:]).strip()
        else:
            body = "\n".join(current_section).strip()
            
        body_lines = body.split("\n")
        for b_line in body_lines:
            b_line = b_line.strip()
            if not b_line:
                continue
                
            # Render bullet points nicely
            if b_line.startswith("-") or b_line.startswith("*"):
                cleaned = b_line.lstrip("-* ").strip()
                pdf.set_x(24) # Indent bullets
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(124, 58, 237)
                pdf.write(5, "-  ")
                pdf.set_text_color(51, 65, 85)
                
                # Check for "Insight:" inline styling
                if "Insight:" in cleaned:
                    parts = cleaned.split("Insight:", 1)
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.write(5, parts[0])
                    pdf.set_font("Helvetica", "I", 10)
                    pdf.set_text_color(100, 116, 139)
                    pdf.write(5, " Insight:" + parts[1] + "\n")
                else:
                    pdf.set_font("Helvetica", "", 10)
                    pdf.write(5, cleaned + "\n")
                pdf.ln(1)
            # Render strategic numbered items
            elif re.match(r'^\d+\.\s+', b_line) or re.match(r'^[a-z]\)\s+', b_line):
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(17, 24, 39)
                pdf.multi_cell(0, 5, b_line)
                pdf.ln(1)
            # Regular text paragraphs
            else:
                pdf.body_text(b_line)
                
        pdf.ln(2)
        current_section.clear()

    for line in lines:
        cleaned_line = line.strip()
        if not cleaned_line:
            continue
            
        # Detect start of a new section
        if re.match(r'^\d+\.\s+[A-Z\s&]+', cleaned_line) or (cleaned_line.isupper() and len(cleaned_line) > 5 and not cleaned_line.startswith("-")):
            flush_section()
            
        current_section.append(line)
        
    flush_section() # Flush any remaining text
    
    return bytes(pdf.output())
